### ISSUE TITLE
[enhancement] All keeping comments on same line

### ISSUE THREAD

**Issue by hazendaz** [revelc/xml-formatter#4]
I have a use case where I put notes beside property versions as comments for next version to  upgrade to.

Example

```xml
<xml-formatter.version>0.1.0</xml-formatter.version> <!-- TODO: Bump to 0.1.1 -->
```
It would be nice to be able to keep this on same line.  No xml formatter thus far has been able to do so.

Example property for this.

keepCommentsSameLine=true

What occurs now..

```xml
<xml-formatter.version>0.1.0</xml-formatter.version>
<!-- TODO: Bump to 0.1.1 -->
```

**Comment by ctubbsii** [comment]
sortpom has some limited support for that: https://github.com/Ekryd/sortpom/wiki/IgnoringSections

**Comment by ctubbsii** [comment]
You could also leave notes as XML attributes instead of comments.

**Comment by hazendaz** [comment]
That support in sortpom is a bit ugly and would sort of defeat my purpose.   Interested in the attribute suggestion.  Assuming maven would simply ignore it and it might look like the following?

```xml
<xml-formatter.version nextVersion="Bump to 0.1.1">0.1.0</xml-formatter.version>
```

**Comment by hazendaz** [comment]
@ctubbsii I'm good now.  I switched to using attributes and it solves my issue without much hassle so I don't need this now :)

**Comment by Elisedlund-ericsson** [comment]
we have had similar issue to this, and think making it configurable is still a good idea
the workaround of using attributes is not even remotely an viable option for us.
